name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v1.2.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required to create releases and upload assets
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install vsce
        run: npm install -g @vscode/vsce
      
      - name: Package extension
        run: vsce package
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.vsix'
          generate_release_notes: true
          draft: false
          prerelease: false
          body: |
            ## 🎉 Cyberdeck 2025 v${{ steps.get_version.outputs.VERSION }}
            
            ### Installation
            
            **From VS Code Marketplace (Recommended):**
            1. Open VS Code
            2. Go to Extensions (Ctrl+Shift+X / Cmd+Shift+X)
            3. Search for "Cyberdeck 2025"
            4. Click Install
            
            **From VSIX file:**
            1. Download the `.vsix` file below
            2. Open VS Code
            3. Go to Extensions (Ctrl+Shift+X / Cmd+Shift+X)
            4. Click the "..." menu → "Install from VSIX..."
            5. Select the downloaded file
            
            **From command line:**
            ```bash
            code --install-extension cyberdeck-2025-${{ steps.get_version.outputs.VERSION }}.vsix
            ```
            
            ### What's Changed
            See the [CHANGELOG](https://github.com/ex1tium/cyberdeck-2025_vscode_theme/blob/main/CHANGELOG.md) for detailed changes.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

